Controllers/AlterarSenhaController.cs
using Microsoft.AspNetCore.Mvc;
using SiteMVC.Helper;
using SiteMVC.Models;
using SiteMVC.Repositorio;

namespace SiteMVC.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _sessao = sessao;
            _usuarioRepositorio = usuarioRepositorio;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel sessaousuarioAtual = _sessao.BuscarSessao();

                    alterarSenhaModel.Id = sessaousuarioAtual.Id;

                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);

                    TempData["success"] = "Senha alterada com sucesso";
                }
            }
            catch (Exception)
            {
                TempData["error"] = "Login e/ou senha inválido(s)";
                throw;
            }
            return View("Index", alterarSenhaModel);
        }
    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using SiteMVC.Filters;
using SiteMVC.Helper;
using SiteMVC.Models;
using SiteMVC.Repositorio;

namespace SiteMVC.Controllers
{
    [PaginaUsuarioLogado]
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        private readonly ISessao _sessao;
        public ContatoController(IContatoRepositorio contatoRepositorio, ISessao sessao)
        {
            _contatoRepositorio = contatoRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioAtual = _sessao.BuscarSessao();
            List<ContatoModel> contatos = _contatoRepositorio.ListarContatos(usuarioAtual.Id);
            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["success"] = "Contato criado com sucesso.";
                    _contatoRepositorio.Adicionar(contato);
                    return RedirectToAction("Index");
                }
                return View(contato);

            }
            catch (Exception)
            {
                TempData["error"] = "Ih, deu alguma merda aí na hora de criar o contato, irmão.";
                return View(contato);
            }

        }

        public IActionResult PaginaEditar(int id)
        {
            ContatoModel contato = _contatoRepositorio.BuscarContato(id);
            return View(contato);
        }

        //[HttpPost]
        public IActionResult Editar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["success"] = "Contato editado com sucesso.";
                    _contatoRepositorio.Editar(contato);
                    return RedirectToAction("Index");
                }
                return View("PaginaEditar", contato);
            }
            catch (Exception)
            {
                TempData["error"] = "Mlk, deu alguma merda aí ao editar.";
                throw;
            }

        }

        public IActionResult BuscarContato()
        {
            return View();
        }

        public IActionResult ConfirmarDelecao(int id)
        {
            ContatoModel contato = _contatoRepositorio.BuscarContato(id);
            return View(contato);
        }

        public IActionResult Deletar(int id)
        {
            try
            {
                bool deletado = _contatoRepositorio.Deletar(id);
                if (deletado)
                {
                    TempData["success"] = "Contato deletado com sucesso.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "KKKKKKKKKKKKKKKK Deu merda, o apagar foi de comes e bebes";
                }
            }
            catch (Exception)
            {
                TempData["error"] = "KKKKKKKKKKKKKKKK Deu merda, o apagar foi de comes e bebes";
                return RedirectToAction("Index");
            }

            return NotFound();
        }
    }
}

Views/AlterarSenha/Index.cshtml
@model AlterarSenhaModel

@{
    Layout = "_LayoutDeslogado";
    ViewData["Title"] = "Alerar senha do usuário";
}


<p>Página de login</p>
@if (TempData["error"] != null)
{
    <div class="container-alert">
        <br />
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["error"]
        </div>
    </div>
}

@if (TempData["success"] != null)
{
    <div class="container-alert">
        <br />
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["success"]
        </div>
    </div>
}


<form asp-action="Alterar" asp-controller="AlterarSenha">
    <div class="mb-3">
        <label for="login" class="form-label">Senha atual</label>
        <input asp-for="SenhaAtual" type="password" class="form-control" id="senha" placeholder="Digite a senha atual" />
        @Html.ValidationMessageFor(x => x.SenhaAtual)
    </div>
    <div class="mb-3">
        <label for="novaSenha" class="form-label">Nova senha</label>
        <input asp-for="NovaSenha" type="password" class="form-control" id="NovaSenha" placeholder="Digite a nova senha">
        @Html.ValidationMessageFor( x => x.NovaSenha)
    </div>
    <div class="mb-3">
        <label for="novaSenhaConfirmacao" class="form-label">Confirme a nova senha</label>
        <input asp-for="NovaSenhaConfirmacao" type="password" class="form-control" id="NovaSenhaconfirmacao" placeholder="Confirme a nova senha">
        @Html.ValidationMessageFor( x => x.NovaSenhaConfirmacao)
    </div>
    <a asp-controller="Contato" asp-action="Index" class="btn btn-secondary">Voltar</a>
    <button type="submit" class="btn btn-primary">Alterar</button>
</form>